swagger: '2.0'
info:
  title: CM TECH - Valid
  description: >-
    Documentação do CM Valid Swagger <br> <ul><li>Para suporte, envie um e-mail
    para suporte@cmtecnologia.com.br contendo no título <b>#CMValid</b> e no
    corpo o ID do response ou request realizado;</li><li>Para dúvidas, envie um
    e-mail para valid@cmtecnologia.com.br;</li><li>Para testes, realize o
    download do <a href='https://www.getpostman.com/downloads/'
    target='_blank'>Postman</a> e importe o <b>JSON</b> com o modelo dos <a
    href='https://s3-sa-east-1.amazonaws.com/valid-docs.cmtecnologia.com.br/CM_Tech_Valid_postman_collection.json'
    target='_blank'>requests</a>;</li><li>Para acompanhar nossas atualizações
    acesse nosso <a href='https://valid-releases.cmtecnologia.com.br/'
    target='_blank'>Release Notes</a>;</li></ul>
  version: "7.6.0"
servers:
  - url: 'https://api-gw.cmtecnologia.com.br/v1/mod-valid'
    description: Production server (uses live data)
    
paths:
  
  /example/eligible:
    get:
      servers:
      - url: https://api-gw.cmtecnologia.com.br/v1
      summary: Retorna o request de exemplo de elegibilidade.
      description: Retorna o request de exemplo da elegibilidade de um determinado convênio.
      parameters:
        - name: id
          in: query
          description: ID do convênio.
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                statusCode: 200
                covenantName: care-plus
                request_example:
                  covenant:
                    id: "c3ad6ffc-d0f2-4d75-b7d5-e264d7484f53"
                    card_number: CARD_NUMBER
                    credentials:
                      code: CODE
                      user: USER
                      password: PASSWORD
                  tiss:
                    version: ''
                    body: {}
                
        5XX:
          description: Unexpected error.
  
  /example/authorize:
    get:
      servers:
      - url: https://api-gw.cmtecnologia.com.br/v1
      summary: Retorna o request de exemplo da autorização.
      parameters:
        - name: id
          in: query
          description: ID do convênio.
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  statusCode: 200
                  covenantName: care-plus
                  request_example:
                    service_character: ''
                    clinical_indication: ''
                    comments: ''
                    procedure_type: ''
                    type_service: ''
                    covenant:
                      id: "7a9a09bf-610f-4ce9-ae6b-ced642b94f3b"
                      credentials:
                        user: ''
                        password: ''
                    medic_requester:
                      type_council: ''
                      number_council: ''
                      cbo: ''
                    medic_executor:
                      type_council: ''
                      number_council: ''
                      cbo: ''
                    procedures:
                      - tuss: ''
                        desc: ''
                        amount: ''
                      - tuss: ''
                        desc: ''
                        amount: ''
                    patient:
                      name: ''
                      newborn: ''
                      card_number: ''
                    attachments:
                      - type: ''
                        description: ''
                        filename: ''
                        file: ''
                    tiss:
                      version: ''
                      body: {}
                  
        5XX:
          description: Unexpected error.
          
  /covenants:
    get:
      summary: Retorna convênio(s) vinculado a conta.
      description: >-
        Método utilizado para retornar um convênio vinculado a sua conta, caso
        não tenha nenhum convênio com o id utilizado, será retornado uma lista
        com todos os convênios.
      parameters:
        - name: Content-Type
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
        - name: X-API-KEY
          in: header
          required: true
          style: simple
          explode: false
          description: Chave de acesso do cliente
          schema:
            type: string
        - name: Accept
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
        - name: id
          in: query
          description: ID do convênio
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CovenantsResponse'
        5XX:
          description: Unexpected error.
  /eligible:
    post:
      summary: Verifica eligibilidade de um beneficiário.
      parameters:
        - name: Content-Type
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
        - name: X-API-KEY
          in: header
          description: Chave de acesso do cliente
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:  
              type: object
              title: cmvInputData
              required:
                - covenant
                - patient
              properties:
                covenant:
                  type: object
                  title: The Covenant Schema
                  required:
                    - id
                    - credentials
                  properties:
                    id:
                      type: string
                      title: ID (UUID4) from /covenants to identify covenant
                      example: "062d71cb-34f7-47ab-8ad9-8bd12a3ce180"
                      pattern: ^(.*)$
                    credentials:
                      type: object
                      title: Credentials from /covenants to login in covenant website
                      example:
                        cpf: cpf_value
                        cnpj: cnpj_value
                        code: code_value
                        user: user_value
                        password: password_value
                date:
                  type: string
                  title: Date
                  example: "27/10/2019"
                procedures:
                  type: array
                  title: List of objects with procedures
                  items:
                    type: object
                type_consultation:
                  type: string
                  title: Type of consultation
                  example: 'Atendimento Externo'
                patient:
                  type: object
                  title: Data of patient
                  required:
                    - card_number
                  properties:
                    newborn:
                      type: string
                      title: New born patient
                      example: 'true'
                    cpf:
                      type: string
                      title: CPF
                    name:
                      type: string
                      title: Name of patient
                    card_number:
                      type: string
                      title: Card number from patient (Alphanumeric ?)
                      example: "0123456789"
                      pattern: ^(.*)$
                medic_executor:
                  type: object
                  properties:
                    cbo:
                      type: string
                      title: CBO
                    region:
                      type: string
                      title: Region
                    type_council:
                      type: string
                      title: Type of council (CRM)
                    number_council:
                      type: string
                      title: Number of council
                provider:
                  type: object
                  properties:
                    city:
                      type: string
                      title: City
                    region:
                      type: string
                      title: Region
                    district:
                      type: string
                      title: District
              
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Response Eligible
                required:
                  - status
                  - patient
                  - id
                properties:
                  status:
                    type: string
                    enum:
                      - 'true'
                      - 'false'
                  patient:
                    type: object
                    properties:
                      name:
                        type: string
                        title: Name of patient
                  id:
                    type: string
                    title: UUID
                
        5XX:
          description: Unexpected error.
          
  /data:
    post:
      servers:
      - url: https://api-gw.cmtecnologia.com.br/v1
      summary: Retorna informações de um beneficiário.
      parameters:
        - name: Content-Type
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
        - name: X-API-KEY
          in: header
          description: Chave de acesso do cliente
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: cmvInputData
              required:
                - covenant
                - patient
              properties:
                covenant:
                  type: object
                  title: The Covenant Schema
                  required:
                    - id
                    - credentials
                  properties:
                    id:
                      type: string
                      title: ID (UUID4) from /covenants to identify covenant
                      example: "062d71cb-34f7-47ab-8ad9-8bd12a3ce180"
                      pattern: ^(.*)$
                    credentials:
                      type: object
                      title: Credentials from /covenants to login in covenant website
                      example:
                        cpf: cpf_value
                        cnpj: cnpj_value
                        code: code_value
                        user: user_value
                        password: password_value
                patient:
                  type: object
                  title: Data of patient
                  required:
                    - card_number
                  properties:
                    card_number:
                      type: string
                      title: Card number from patient (Alphanumeric ?)
                      example: "0123456789"
                      pattern: ^(.*)$
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: cmvOutputData
                required:
                  - covenant
                  - patient
                  - provider
                  - id
                properties:
                  patient:
                    type: object
                    required:
                      - name
                      - gender
                      - card_number
                      - birth
                      - cpf
                      - address
                      - contact
                      - cns
                      - plan
                    properties:
                      name:
                        type: string
                        title: Name of patient
                      gender:
                        type: string
                        title: Gender
                        example: "F/M"
                      card_number:
                        type: string
                        title: Card number from patient (Alphanumeric ?)
                        example: "0123456789"
                        pattern: ^(.*)$
                      birth:
                        type: string
                        title: Date of birth
                        pattern: '/^[0-9]{2}[/]{1}[0-9]{2}[/]{1}[0-9]{4}$/g'
                        example: "DD/MM/AAAA"
                      cpf:
                        type: string
                        title: CPF
                      address:
                        type: object
                        title: Address
                      contact:
                        type: object
                        title: Contact
                      cns:
                        type: string
                        title: CNS
                        example: '706400626617081'
                      plan:
                        type: object
                        required:
                          - code
                          - network
                          - name
                          - accommodation
                          - segment
                          - product
                          - companion
                        properties:
                          code:
                            type: string
                            title: Code of plan
                          network:
                            type: string
                            title: Plan network
                          name:
                            type: string
                            title: Name of plan
                          accommodation:
                            type: string
                            title: Accomodation
                          segment:
                            type: string
                            title: Segment
                          product:
                            type: string
                            title: Product name
                          companion:
                            type: string
                            title: Companion
                  covenant:
                    type: object
                    required:
                      - id
                      - name
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                        title: Name of covenant
                  id:
                    type: string
                    title: UUID
                
        5XX:
          description: Unexpected error.
          
  /authorize:
    post:
      summary: Requisita autorização para o convênio.
      parameters:
        - name: Content-Type
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
        - name: X-API-KEY
          in: header
          description: Adicionar sua CHAVE da aplicação.
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          required: true
          style: simple
          explode: false
          description: application/json
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              #$ref: '#/components/schemas/AuthorizeBody'
              type: object
              title: request Authorize
              required:
                - covenant
                - patient
                - procedures
                - medic_requester
                - type_service
                - procedure_type
              properties:
                covenant:
                  type: object
                  title: The Covenant Schema
                  required:
                    - id
                    - credentials
                  properties:
                    id:
                      type: string
                      title: ID (UUID4) to identify covenant
                      example: "062d71cb-34f7-47ab-8ad9-8bd12a3ce180"
                      pattern: ^(.*)$
                    credentials:
                      type: object
                      title: Credentials to login in covenant website
                      required:
                        - user
                        - password
                      properties:
                        code:
                          type: string
                        user:
                          type: string
                        password:
                          type: string
                      example:
                        cpf: cpf_value
                        cnpj: cnpj_value
                        code: code_value
                        user: user_value
                        password: password_value
                comments:
                  type: string
                  title: Comments or Justifications
                guide_number:
                  type: string
                procedure_date:
                  type: string
                  title: The date for the procedure
                  pattern: ^(.*)$
                used_technique:
                  type: string
                  pattern: ^(.*)$
                service_character:
                  type: string
                  enum:
                    - ELT
                    - URG
                type_service:
                  type: string
                  example:
                    SP/SADT
                clinical_indication:
                  type: string
                  title: The clinical indication
                medic_requester:
                  type: object
                  title: The medic requester
                  required:
                    - type_council
                    - number_council
                    - cbo
                  properties:
                    type_council:
                      type: string
                      default: ''
                      example:
                        CRM
                      pattern: ^(.*)$
                    number_council:
                      type: string
                      pattern: ^(.*)$
                    cbo:
                      type: string
                    region:
                      type: string
                      example:
                        MG
                      pattern: ^(.*)$
                    name:
                      type: string
                      title: The Name the medic
                      pattern: ^(.*)$
                medic_executor:
                  type: object
                  title: The medic executor
                  required:
                    - type_council
                    - number_council
                  properties:
                    type_council:
                      type: string
                      title: The council type
                      default: ''
                      example:
                        CRM
                      pattern: ^(.*)$
                    number_council:
                      type: string
                      title: The council number
                      default: ''
                      pattern: ^(.*)$
                patient:
                  type: object
                  required:
                    - card_number
                  properties:
                    name:
                      type: string
                      pattern: ^(.*)$
                    card_number:
                      type: string
                      pattern: ^(.*)$
                    newborn:
                      type: string
                      enum:
                        - 'true'
                        - 'false'
                provider_requester:
                  type: object
                  properties:
                    name:
                      type: string
                    code:
                      type: string
                      
                  # anyOf: 
                  #   - name:
                  #       type: string
                  #       pattern: ^(.*)$
                  #   - code:
                  #       type: string
                  #       pattern: ^(.*)$
                provider_executor:
                  type: object
                  properties:
                    name:
                      type: string
                    code:
                      type: string
                procedures:
                  type: array
                  title: The list of procedures
                  items:
                    type: object
                    required:
                      - tuss
                      - desc
                      - amount
                    properties:
                      tuss:
                        type: string
                        title: The procedure code tuss
                        pattern: ^(.*)$
                      desc:
                        type: string
                        title: The description of the procedure
                        pattern: ^(.*)$
                      amount:
                        type: string
                        title: The requested quantity of the procedure
                        pattern: ^(.*)$
                date:
                  type: string
                  example: '19/04/2018'
                  pattern: ^(.*)$
                procedure_type:
                  type: string
                  example:
                    Execucao
                attachments:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - description
                      - filename
                      - file
                    properties:
                      type:
                        type: string
                        title: the type of the inserted attachment
                        example:
                          Laudo exame
                        pattern: ^(.*)$
                      description:
                        type: string
                        title: A description for the attachment
                        pattern: ^(.*)$
                      filename:
                        type: string
                        example:
                          Laudo.pdf
                        pattern: ^(.*)$
                      file:
                        type: string
                        title: file in base64
                        pattern: ^(.*)$
              
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                #$ref: '#/components/schemas/inline_response_200_2'
                type: object
                title: Request Authorize
                required:
                  - password
                  - provider_guide
                  - status
                  - message
                  - procedures
                  - patient
                  - document_url
                  - id
                  - expiration_date
                properties:
                  password:
                    type: string
                    pattern: ^(.*)$
                  status:
                    type: string
                    enum:
                      - "true"
                      - "false"
                  message:
                    type: string
                    enum:
                      - autorizado
                      - autorizado parcialmente
                      - em análise
                      - negado
                  document_url:
                    type: string
                    pattern: ^(.*)$
                  provider_guide:
                    type: string
                    title: The provider guide number
                  operator_guide:
                    type: string
                    title: The operator guide number
                  expiration_date:
                    type: string
                    title: ''
                  patient:
                    type: object
                    properties:
                      name:
                        type: string
                  procedures:
                    type: array
                    title: The list of procedures
                    items:
                      type: object
                      required:
                        - tuss
                        - desc
                        - amount
                        - authorized_amount
                      properties:
                        tuss:
                          type: string
                          title: The procedure code tuss
                          pattern: ^(.*)$
                        desc:
                          type: string
                          title: The description of the procedure
                          pattern: ^(.*)$
                        amount:
                          type: string
                          title: The requested quantity of the procedure
                          pattern: ^(.*)$
                        authorized_amount:
                          type: string
                          title: The authorized quantity of procedure
                  id:
                    type: string
                    title: ID (UUID4) to identify covenant
                    default: ''
                    example: "062d71cb-34f7-47ab-8ad9-8bd12a3ce180"
                    pattern: ^(.*)$
                
        5XX:
          description: Unexpected error.
  /authorize/status:
    get:
      summary: Consulta solicitação de autorização.
      description: >-
        Método utilizado para retornar um convênio vinculado a sua conta, caso
        não tenha nenhum convênio com o id utilizado, será retornado uma lista
        de convênios.
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: card_number
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: user
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: password
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: protocol
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: protocol_password
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: code
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: cnpj
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: cpf
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: X-API-KEY
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: Accept
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        5XX:
          description: Unexpected error.
components:
  schemas:
    CovenantsResponse:
      type: object
      properties:
        id:
          type: string
          example: 241bef48-ccdc-4d7a-9630-eab21bebc14d
        name:
          type: string
          example: Nome do convênio
        credentials_keys:
          type: array
          example:
            - user
            - password
          items:
            type: string
        ans:
          type: string
          example: '415949'
        cnpj:
          type: string
          example: 99.222.333/0005-29
        type:
          type: string
        organization:
          type: string
          example: PRESTADORA DE SERVIÇOS LTDA
        active:
          type: string
          example: 'true'
        services:
          $ref: '#/components/schemas/CovenantsResponse_services'
    # Covenant:
    #   required:
    #     - card_number
    #     - credentials
    #     - id
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       example: 7ba25083-f311-4b8a-b7de-d32d96c087a1
    #     card_number:
    #       type: string
    #       example: '12345'
    #     credentials:
    #       $ref: '#/components/schemas/Covenant_credentials'
    # EligibleBody:
    #   type: object
    #   properties:
    #     covenant:
    #       $ref: '#/components/schemas/Covenant'
    #     provider:
    #       $ref: '#/components/schemas/EligibleBody_provider'
    #     medic_executor:
    #       $ref: '#/components/schemas/EligibleBody_medic_executor'
    #     date:
    #       type: string
    #       example: 10/05/2019
    #     type_consultation:
    #       type: string
    #       example: Primeira Consulta
    #     patient:
    #       $ref: '#/components/schemas/EligibleBody_patient'
    #     procedures:
    #       type: array
    #       items:
    #         $ref: '#/components/schemas/EligibleBody_procedures'
    # AuthorizeMedicRequester:
    #   required:
    #     - cbo
    #     - crm
    #     - name
    #     - region
    #   type: object
    #   properties:
    #     name:
    #       type: string
    #       example: João da Silva
    #     cbo:
    #       type: string
    #       example: '654321'
    #     region:
    #       type: string
    #       example: MG
    #     crm:
    #       type: string
    #     type_concil:
    #       type: string
    #     number_concil:
    #       type: string
    # AuthorizeProcedures:
    #   required:
    #     - amount
    #     - desc
    #     - tuss
    #   type: object
    #   properties:
    #     tuss:
    #       type: string
    #       example: '10101136'
    #     desc:
    #       type: string
    #       example: Consulta Saúde Ocupacional
    #     amount:
    #       type: string
    #       example: '1'
    #     region:
    #       type: string
    #     face:
    #       type: string
    # AuthorizeBody:
    #   required:
    #     - clinicalIndication
    #     - covenant
    #     - disposition
    #     - medic_requester
    #     - patient_name
    #     - procedureDate
    #     - procedures
    #     - tiss
    #   type: object
    #   properties:
    #     disposition:
    #       type: string
    #       example: ELT
    #       enum:
    #         - ELT
    #         - URG
    #     patient_name:
    #       type: string
    #       example: Jessica
    #     clinicalIndication:
    #       type: string
    #       example: Indicação Clínica ou Hipótese diagnóstica
    #     covenant:
    #       $ref: '#/components/schemas/Covenant'
    #     medic_requester:
    #       $ref: '#/components/schemas/AuthorizeMedicRequester'
    #     procedures:
    #       type: array
    #       example:
    #         - id: '1234567'
    #           name: OBSTETRICA COM DOPPLER COLORIDO
    #           amount: '2'
    #         - id: '1234568'
    #           name: OBSTETRICA COM DOPPLER COLORIDO
    #           amount: '1'
    #       items:
    #         $ref: '#/components/schemas/AuthorizeProcedures'
    #     tiss:
    #       type: object
    inline_response_200_1:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        ans:
          type: string
        cnpj:
          type: string
        organization:
          type: string
        credentials:
          type: string
        active:
          type: string
    # inline_response_200_body_covenant:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #     name:
    #       type: string
    #     card_number:
    #       type: string
    #     plan:
    #       type: string
    #     product:
    #       type: string
    # inline_response_200_body:
    #   required:
    #     - covenant
    #     - pacient_gender
    #     - pacient_name
    #   type: object
    #   properties:
    #     pacient_name:
    #       type: string
    #     pacient_gender:
    #       type: string
    #     covenant:
    #       $ref: '#/components/schemas/inline_response_200_body_covenant'
    # inline_response_200:
    #   required:
    #     - body
    #     - id
    #     - message
    #     - status
    #     - type
    #   type: object
    #   properties:
    #     type:
    #       type: string
    #       example: ELT
    #     protocol:
    #       type: string
    #     password:
    #       type: string
    #     status:
    #       type: string
    #       example: 'true'
    #     return_code:
    #       type: string
    #     return:
    #       type: string
    #     message_code:
    #       type: string
    #     message:
    #       type: object
    #     document:
    #       type: string
    #     body:
    #       $ref: '#/components/schemas/inline_response_200_body'
    # inline_response_200_2_body:
    #   required:
    #     - covenant
    #     - pacient_gender
    #     - pacient_name
    #   type: object
    #   properties:
    #     pacient_name:
    #       type: string
    #     pacient_gender:
    #       type: string
    #     covenant:
    #       $ref: '#/components/schemas/inline_response_200_body_covenant'
    #     medic_requester:
    #       type: object
    #     procedures:
    #       type: array
    #       items:
    #         type: object
    # inline_response_200_2:
    #   required:
    #     - body
    #     - id
    #     - message
    #     - status
    #     - type
    #   type: object
    #   properties:
    #     type:
    #       type: string
    #       example: ELT
    #     protocol:
    #       type: string
    #     password:
    #       type: string
    #     status:
    #       type: string
    #       example: 'false'
    #     return_code:
    #       type: string
    #     return:
    #       type: string
    #     message_code:
    #       type: string
    #     message:
    #       type: object
    #     document:
    #       type: string
    #     body:
    #       $ref: '#/components/schemas/inline_response_200_2_body'
    #     id:
    #       type: string
    CovenantsResponse_services:
      type: object
      properties:
        eligible:
          type: string
          example: 'true'
        authorize:
          type: string
          example: 'false'
        status:
          type: string
          example: 'true'
        cancel:
          type: string
          example: 'true'
    # Covenant_credentials:
    #   required:
    #     - password
    #   type: object
    #   properties:
    #     user:
    #       type: string
    #       example: user
    #     password:
    #       type: string
    #       example: password
    #     code:
    #       type: string
    #       example: '12'
    #     cpf:
    #       type: string
    #       example: '02112545554'
    #     cnpj:
    #       type: string
    #       example: '38709953000104'
    # EligibleBody_provider:
    #   type: object
    #   properties:
    #     type:
    #       type: string
    #       example: Consutorio
    #     city:
    #       type: string
    #       example: Belo Horizonte
    #     district:
    #       type: string
    #       example: Lourdes
    #     region:
    #       type: string
    #       example: MG
    # EligibleBody_medic_executor:
    #   type: object
    #   properties:
    #     type_council:
    #       type: string
    #       example: CRM
    #     number_council:
    #       type: string
    #       example: '11111'
    #     region:
    #       type: string
    #       example: MG
    #     cbo:
    #       type: string
    #       example: '225270'
    # EligibleBody_patient:
    #   type: object
    #   properties:
    #     cpf:
    #       type: string
    #       example: '11111111111'
    #     name:
    #       type: string
    #     cns:
    #       type: string
    #     newborn:
    #       type: string
    # EligibleBody_procedures:
    #   type: object
    #   properties:
    #     tiss:
    #       type: string
